config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  # get 'admin'
  # get 'home/index'

  # get 'admin', to: 'admin#panel', as: :admin_home

  scope 'f' do
    get ':id', to: 'home#show_article', as: :show_article
  end

  get 'feed', to: "home#feed"



  scope 'admin' do
    resources :articles do
      resources :comments
    end
    get '', to: 'admin#panel', as: :admin_home
    get 'settings', to: 'setting#edit', as: :edit_settings
  	patch 'settings/update', to: 'setting#update', as: :update_settings

    get 'editors', to: "admin#index_users", as: :editors
    get 'editor/new-editor', to: "admin#new_user", as: :editor_new
    get 'editor/:id/edit', to: "admin#edit_user", as: :editor_edit
    post 'editor/create', to: "admin#create_user", as: :editor_create
    patch 'editor/update/:id', to: "admin#update_user", as: :editor_update
    delete 'editor/delete', to: "admin#destroy_user", as: :destroy_editor
  end

end

app/models/article.rb
class Article < ApplicationRecord
	
	has_one_attached :cover
  belongs_to :admin
	has_many :comments, dependent: :destroy
	has_and_belongs_to_many :tags

	validates :title, presence: true, length: {in: 10..40}
	validates :text, :category, :publication_day, :cover, presence: true

	Categories = [['Code', 'code'], ['Random', 'random'], ['Tech', 'tech'], ['Science', 'science']]

	scope :default, -> {where(published: true).where('publication_day < ?', DateTime.now).order('created_at desc')}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!

  layout 'dash'

  # Get requests
  def index
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result.order('created_at desc'))


  end
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
    unless (current_admin.id == @article.admin_id) or (current_admin.role == 'admin') or (current_admin.role == 'admin')
      return (redirect_to action: :index, notice: "You can't do that")
    end

  end

  # post requests ...
  def create
    # @article = Article.new(articles_params)
    @article = current_admin.articles.new(articles_params)
    @article.text_compiled = Kramdown::Document.new(@article.text).to_html

    @article.tags.delete_all
    tag_list = params['article']['tags']
    tag_list.shift

    tag_list.each do |tag_name|
      tag = Tag.find_by!(name: tag_name)
      @article.tags << tag
    end


    if @article.save
      redirect_to @article
    else
      render 'new'
    end
    # render plain: params[:article].inspect
  end


  def update
    @article = Article.find(params[:id])
    @article.assign_attributes(articles_params)
    @article.text_compiled = Kramdown::Document.new(@article.text).to_html


    # @article.tags.delete_all
    @article.tags.delete_all
    tag_list = params['article']['tags']
    tag_list.shift

    p '---------------'
    p tag_list
    p '---------------'

    tag_list.each do |tag_name|
      tag = Tag.find_by!(name: tag_name)
      @article.tags << tag
    end


    @article.text_compiled = Kramdown::Document.new(@article.text).to_html

    if @article.save
      redirect_to @article
    else
      render 'edit'
    end
  end


  def destroy
    @article = Article.find(params[:id])
    @article.cover.purge
    @article.destroy
 
    redirect_to articles_path
  end

  private
    def articles_params
      params.require(:article).permit(:publication_day, :admin_id, :title, :text, :cover, :url_cover, :url_img1, :url_img2, :url_img3, :published, :category, :short_desc)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_action_bar.html.erb
<div class="action-bar">
	<div class="title" id="menu_btn">
		<i class="fas fa-ellipsis-h fa-lg"></i>
		<a href="<%= request.url %>">
			<%= image_tag 'bits_soup.svg' %>
		</a>
	</div>
	<div class="icons">
	</div>
</div>

app/views/articles/_form.html.erb
<div class="container">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= articles_path %>">Articles</a></li>
      <% if action_name == 'edit' %>
        <li class="breadcrumb-item active" aria-current="page">Edit article</li>
        
      <% else %>
        <li class="breadcrumb-item active" aria-current="page">New article</li>
      <% end %>

      
    </ol>
  </nav>
  
  <div class="col-md-12">

    <% if @article.cover.attached? %>
      <p>
        <%= image_tag @article.cover, width: 200 %>
      </p>
    <% end %>
    
  </div>
  
  <%= form_with model: @article, url: url, local: true do |f| %>
    
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <p>
          <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
        </p>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %> 
        </ul>
      </div>
      
    <% end %>
      
      <div class="form-group">
        <%= f.file_field :cover, accept: "image/*", direct_upload: true %>
      </div>
      
      <div class="form-group">
        <%= f.label :published %>
        <%= f.check_box :published %>
      </div>
      

      <div class="form-group">
        <%= f.label :publication_day %>
        <%= f.datetime_local_field :publication_day, class: 'form-control', required: true %>
      </div>

      <br>
      <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category, options_for_select(Article::Categories), {}, {class: "select_1"} %>
      </div>
     
      <div class="form-group">
        <%= f.label :tags %>
        <%= f.collection_select :tags, Tag.all, :name, :name, {}, {class: "select_2", multiple: true} %>  
      </div>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :short_desc, "Short intro to the article (20-50 characters)" %>
        <%= f.text_field :short_desc, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :text, "Text (you can use Markdown)" %>
        <%= f.text_area :text, class: "form-control", rows: 30 %>
      </div>
    

        <%= f.submit "Save", class: "btn btn-primary btn-round" %>

    <p>
    </p>
  <% end %>

</div>
       

<script type="text/javascript">

  new SlimSelect({
    select: '.select_1'
  })

  new SlimSelect({
    select: '.select_2'
  })

</script>

app/views/articles/edit.html.erb
<% @title = "Edit article" %>
<%= render 'action_bar' %>
<%= render 'form', url: article_path(@article) %>

app/views/articles/index.html.erb
<% @title = "Articles" %>

<%= render 'action_bar' %>

<div class="container">

	<nav class="index_nav navbar navbar-expand-lg navbar-light bg-light rounded">
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarsExample09" style="">
      <ul class="navbar-nav mr-auto">
       
        <li class="nav-item">
          <a class="nav-link" href="<%= new_article_path %>">
						<i class="fas fa-plus"></i>
	          New article
        	</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= articles_path %>">
						<i class="fas fa-eraser"></i>

	          Reset search
        	</a>
        </li>
        

      </ul>
     
      <%= search_form_for @q, class: "form-inline" do |f| %>
					<div class="input-group">
				  	<%= f.search_field :title_or_admin_full_name_cont, placeholder: "Search title or author", class: 'form-control' %>

						<div class="input-group-append">
					    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
					    	<i class="fas fa-search"></i>
					    </button>
					  </div>
					</div>	

			<% end %>
    </div>
  </nav>


  <div class="articles_index my-3 p-3 bg-white rounded shadow-sm">

  	<% @articles.each do |a| %>
	    <div class="media text-muted pt-3">
	      <div class="article_img mr-2" style="background: <%= a.color %>"></div>
	      <p class="media-body pb-3 mb-0 small lh-125 m border-gray">
	      	<b class="title"><%= a.title %></b> 
	        <b class="text-gray-dark"><%= a.admin.full_name %></b> <br>
	        <%= truncate(a.short_desc, length: 50) %><br>
	        <b>Views: </b><%= a.views %><br>
	        <b>Category: </b><%= a.category.humanize %><br>
	        <b>Creation: </b><%= a.created_at.strftime('%m-%d-%Y %I:%M %p') %><br>
	        <b>Publication: </b><%= a.publication_day.strftime('%m-%d-%Y %I:%M %p') %>
	      </p>
	      <% if a.published %>
					<i class="fas fa-check" style="color: green" data-toggle="tooltip" data-placement="top" title="Published"></i>
					<a href="<%= show_article_path(a) %>" data-toggle="tooltip" data-placement="top" title="See at front">
						<i class="fas fa-share"></i>
					</a>
				<% else %>
					<i class="fas fa-exclamation-triangle" style="color: orange" data-toggle="tooltip" data-placement="top" title="Unpublished"></i>
				<% end %>
					
				<a href="<%= article_path(a) %>" data-toggle="tooltip" data-placement="top" title="Preview">
					<i class="fas fa-eye"></i>
				</a>

					<% if (current_admin.id == a.admin_id) or (current_admin.role == 'admin') or (current_admin.role == 'super')  %>
						<a href="<%= edit_article_path(a) %>" data-toggle="tooltip" data-placement="top" title="Edit">
							<i class="far fa-edit"></i></a>
					<% end %>

					<% if current_admin.role == 'super' or current_admin.role == 'admin' %>
						<%= link_to article_path(a), method: :delete, data: {confirm: 'Are you sure?'} do %>
							<i class="far fa-trash-alt" style="color: red"></i>
						<% end %>
							
					<% end %>

	    </div>
  		
  	<% end %>

    
  </div>	


	<%= pagy_nav_bootstrap(@pagy).html_safe %>

</div>

app/views/articles/new.html.erb
<% @title = "New article" %>

<%= render 'action_bar' %>
<%= render 'form', url: articles_path %>

app/views/articles/show.html.erb
<% @title = "See article" %>
<%= render 'action_bar' %>

<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="<%= articles_path %>">Articles</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Show article</li>
	    <li class="breadcrumb-item active"><a href="<%= edit_article_path(@article) %>">Edit article</a></li>
	  </ol>
	</nav>
	
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div class="admin_show_article">
						<% if @article.cover.attached? %>
							<p>
								<%= image_tag @article.cover %>
							</p>
						<% end %>
						<p>
							<b>Author:</b>
							<%= @article.admin.full_name %>
						</p>

						<p>
							<b>Title:</b> 
							<%= @article.title %>
						</p>

						<p>
							<b>Tags: </b>
							<% @article.tags.each do |tag| %>
								<span class="badge badge-warning"><%= tag.name %></span>
							<% end %>
						</p>

						<% if @article.short_desc.size > 0 %>
							<p>
								<b>Short intro: </b>
								<%= @article.short_desc %>
							</p>
							
						<% end %>
						


						<%= @article.text_compiled.html_safe %>
						<br>

						<h3>Comments</h3>
						<%= render @article.comments %>

						<h3>Add a comment:</h3>
						<%= render 'comments/form' %>
						
					</div>
						

					
				</div>
				
			</div>
		</div>
		
	</div>
</div>