config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  # get 'admin'
  # get 'home/index'

  # get 'admin', to: 'admin#panel', as: :admin_home

  scope 'f' do
    get ':id', to: 'home#show_article', as: :show_article
  end

  get 'feed', to: "home#feed"



  scope 'admin' do
    resources :articles do
      resources :comments
    end
    get '', to: 'admin#panel', as: :admin_home
    get 'settings', to: 'setting#edit', as: :edit_settings
  	patch 'settings/update', to: 'setting#update', as: :update_settings

    get 'editors', to: "admin#index_users", as: :editors
    get 'editor/new-editor', to: "admin#new_user", as: :editor_new
    get 'editor/:id/edit', to: "admin#edit_user", as: :editor_edit
    post 'editor/create', to: "admin#create_user", as: :editor_create
    patch 'editor/update/:id', to: "admin#update_user", as: :editor_update
    delete 'editor/delete', to: "admin#destroy_user", as: :destroy_editor
  end

end

app/views/admin/_action_bar.html.erb
<div class="action-bar">
	<div class="title" id="menu_btn">
		<i class="fas fa-ellipsis-h fa-lg"></i>
		<a href="<%= request.url %>">
			<%= image_tag 'bits_soup.svg' %>
		</a>
	</div>
	<div class="icons">
		<i class="fas fa-search fa-lg"></i>
	</div>
</div>

app/views/admin/_form.html.erb
<div class="container">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= editors_path %>">Editors</a></li>
      <% if action_name == 'edit' %>
        <li class="breadcrumb-item active" aria-current="page">Edit editor</li>
        
      <% else %>
        <li class="breadcrumb-item active" aria-current="page">New editor</li>
      <% end %>

      
    </ol>
  </nav>
  
  
  <%= form_with model: @user, url: url, local: true do |f| %>
    
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <p>
          <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
        </p>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %> 
        </ul>
      </div>
      
    <% end %>
   
     <% unless current_admin.role == 'super' %>
      <div class="form-group">
        <%= f.label :role %>
        <%= f.select :role, options_for_select(Admin::Roles), {}, {class: "select_1"} %>
      </div>
       
     <% end %>
     


      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :full_name %>
            <%= f.text_field :full_name, class: "form-control" %>
          </div>
          
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: "form-control" %>
          </div>
          
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :p_twitter, "Twitter profile" %>
            <%= f.text_field :p_twitter, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :p_instagram, "Instagram profile" %>
            <%= f.text_field :p_instagram, class: "form-control" %>
          </div>
          
        </div>
      </div>
      <br>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          
        </div>
        <% if action_name == 'new' %>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
        <% else %>
          <div class="col-md-6">
            <div class="form-group" id="edit_password">
              <span id="link_edit_pass" class="link">Edit password</span>
            </div>
          </div>
        <% end %>
        
      </div>


      
    

        <%= f.submit "Save", class: "btn btn-primary btn-round" %>

    <p>
    </p>
  <% end %>

</div>
       

<script type="text/javascript">

  new SlimSelect({
    select: '.select_1'
  })

 

</script>

app/views/admin/edit_user.html.erb
<% @title = "Editor editor" %>

<%= render 'action_bar' %>

<%= render 'form', url: editor_update_path(id: @user.id) %>

app/views/admin/index_users.html.erb
<% @title = "Editors" %>

<%= render 'action_bar' %>


<div class="container">

	<nav class="index_nav navbar navbar-expand-lg navbar-light bg-light rounded">
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarsExample09" style="">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= editor_new_path %>">
						<i class="fas fa-plus"></i>
	          New editor
        	</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= editors_path %>">
						<i class="fas fa-eraser"></i>
	          Reset search
        	</a>
        </li>
        

      </ul>
     
      <%= search_form_for @q, url: editors_path,class: "form-inline" do |f| %>
					<div class="input-group">
				  	<%= f.search_field :full_name_or_username_or_email_cont, placeholder: "Search title or author", class: 'form-control' %>

						<div class="input-group-append">
					    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
					    	<i class="fas fa-search"></i>
					    </button>
					  </div>
					</div>	

			<% end %>
    </div>
  </nav>


  <div class="articles_index my-3 p-3 bg-white rounded shadow-sm">

  	<% @users.each do |u| %>
	    <div class="media text-muted pt-3">
	      <%= image_tag 'man.svg', size: '37' %>
	      <p class="media-body pb-3 mb-0 small lh-125 m border-gray">
	      	<b class="title"><%= u.full_name %></b> 
	        <b class="text-gray-dark"><%= u.email %></b> <br>
	        <b>Username: </b><%= u.username %><br>
	        <b>Role: </b><%= u.role %><br>
	        <b>Twitter: </b><%= u.p_twitter %><br>
	        <b>Instagram </b><%= u.p_instagram %>
	      </p>
	      
					
			

				<% if (current_admin.id == u.id) or (current_admin.role == 'super') or (current_admin.role == 'admin') %>
					<a href="<%= editor_edit_path(u) %>" data-toggle="tooltip" data-placement="top" title="Edit">
						<i class="far fa-edit"></i>
					</a>
				<% end %>

				<% if current_admin.role == 'super' or current_admin.role == 'admin' %>
					<%= link_to destroy_editor_path(id: u.id), method: :delete, data: {confirm: 'Are you sure?'} do %>
						<i class="far fa-trash-alt" style="color: red"></i>
					<% end %>
						
				<% end %>

	    </div>
  		
  	<% end %>

    
  </div>	


	<%= pagy_nav_bootstrap(@pagy).html_safe %>

</div>

app/views/admin/new_user.html.erb
<% @title = "New editor" %>

<%= render 'action_bar' %>

<%= render 'form', url: editor_create_path %>

app/views/admin/panel.html.erb
<% @title = "Panel de control" %>

<%= render 'action_bar' %>

<div class="container">
	
	<div class="panel_box">
		<h5 class="title">Articulos publicados</h5>
		<span class="number"><%= @posts %></span>
	</div>
	
	<div class="panel_box">
		<h5 class="title">Usuarios activos por dia</h5>
		<span class="number">88,000</span>
	</div>
</div>