config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  # get 'admin'
  # get 'home/index'

  # get 'admin', to: 'admin#panel', as: :admin_home

  scope 'f' do
    get ':id', to: 'home#show_article', as: :show_article
  end

  get 'feed', to: "home#feed"



  scope 'admin' do
    resources :articles do
      resources :comments
    end
    get '', to: 'admin#panel', as: :admin_home
    get 'settings', to: 'setting#edit', as: :edit_settings
  	patch 'settings/update', to: 'setting#update', as: :update_settings

    get 'editors', to: "admin#index_users", as: :editors
    get 'editor/new-editor', to: "admin#new_user", as: :editor_new
    get 'editor/:id/edit', to: "admin#edit_user", as: :editor_edit
    post 'editor/create', to: "admin#create_user", as: :editor_create
    patch 'editor/update/:id', to: "admin#update_user", as: :editor_update
    delete 'editor/delete', to: "admin#destroy_user", as: :destroy_editor
  end

end

app/views/shared/_action_bar_front.html.erb

<div class="action-bar">
	<div class="title" id="menu_btn">
		<% if admin_signed_in? %>
			<i class="fas fa-ellipsis-h fa-lg"></i>
			
		<% else %>
			<i class=""></i>
		<% end %>
		
		<a href="<%= root_path %>">
			<%= image_tag 'bits_soup.svg' %>
		</a>
	</div>
	<div class="icons search_form_front">
		<%= search_form_for @q, url: root_path do |f| %>
  		<%= f.search_field :title_or_short_desc_cont, class: '' %>

		<% end %>
	</div>
</div>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script>


var disqus_config = function () {
	this.page.url = "<%= request.url %>";  // Replace PAGE_URL with your page's canonical URL variable
	// this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://<%= @setting.disqus_id %>.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/shared/_footer.html.erb
<footer class="blog_footer">
	<div class="container">
		<p>© BitsSoup 2018-2019, Angel Padilla.</p>
		<p></p>
		
	</div>
</footer>

app/views/shared/_google_an.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= @setting.g_analytics %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= @setting.g_analytics %>');
</script>

app/views/shared/_side_nav.html.erb
<div class="side-nav">
	<header>
		<div class="avatars-container">
				<img src="https://img.buzzfeed.com/buzzfeed-static/static/2015-12/12/17/user_images/webdr10/mattortile-v2-24953-1449958659-0_large.jpg?downsize=715:*&output-format=auto&output-quality=auto" width=70 height=70/>
		</div>
		<div class="rich-area">
			<a href="#!"><%= current_admin.full_name %></a>

			<div class="email">
				<a href="#!"><%= current_admin.email %></a>
			</div> 
		</div>
	</header>
	<nav>
		<ul>
			<% if current_admin.role == 'super' or current_admin.role == 'admin' %>
				<li>
					<a href="<%= admin_home_path %>">
						<i class="fas fa-tachometer-alt fa-lg"></i>
						Panel
					</a>
				</li>
			<% end %>
			
			<li>
				<a href="<%= articles_path %>">
					<i class="fas fa-newspaper fa-lg"></i>
					Articles
				</a>
			</li>
			<% if current_admin.role == 'super' or current_admin.role == 'admin' %>
				<li>
					<a href="<%= editors_path %>">
						<i class="fas fa-users fa-lg"></i>
						Editors
					</a>
				</li>
			<% end %>
			

			<hr>
			<li id='subheader'>Options</li>
			<% if current_admin.role == 'super' %>
				<li>
					<a href="<%= edit_settings_path %>">
							<i class="fas fa-cog"></i>
							Options
					</a>
				</li>
				
			<% end %>
			
			<li>
				<a href="<%= root_path %>">
						<i class="fas fa-store"></i> Go to front
				</a>
			</li>
			<li>
				<%= link_to destroy_admin_session_path, method: :delete do %>
					<i class="fas fa-sign-out-alt"></i> Log out
				<% end %>
			</li>

			
		</ul>
	</nav>
</div>