config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  # get 'admin'
  # get 'home/index'

  # get 'admin', to: 'admin#panel', as: :admin_home

  scope 'f' do
    get ':id', to: 'home#show_article', as: :show_article
  end

  get 'feed', to: "home#feed"



  scope 'admin' do
    resources :articles do
      resources :comments
    end
    get '', to: 'admin#panel', as: :admin_home
    get 'settings', to: 'setting#edit', as: :edit_settings
  	patch 'settings/update', to: 'setting#update', as: :update_settings

    get 'editors', to: "admin#index_users", as: :editors
    get 'editor/new-editor', to: "admin#new_user", as: :editor_new
    get 'editor/:id/edit', to: "admin#edit_user", as: :editor_edit
    post 'editor/create', to: "admin#create_user", as: :editor_create
    patch 'editor/update/:id', to: "admin#update_user", as: :editor_update
    delete 'editor/delete', to: "admin#destroy_user", as: :destroy_editor
  end

end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/setting_controller.rb
include Methods

class SettingController < ApplicationController
	before_action :authenticate_admin!, :only_super

  layout 'dash'
  
	def edit
		

	end

	def update
		if @setting.update(settings_params)
			return (redirect_to(edit_settings_path, notice: "Settings updated!"))
		else
			render 'edit'
		end
	end

	private

    def settings_params
      params.require(:setting).permit(:disqus_id, :name, :g_analytics, :post_page)
    end
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/views/setting/_action_bar.html.erb
<div class="action-bar">
	<div class="title" id="menu_btn">
		<i class="fas fa-ellipsis-h fa-lg"></i>
		<a href="<%= request.url %>">
			<%= image_tag 'bits_soup.svg' %>
		</a>
	</div>
	<div class="icons">
	</div>
</div>

app/views/setting/edit.html.erb
<% @title = "Settings" %>

<%= render 'action_bar' %>

<div class="container">
	<h5>Settings</h5>
	<br>
  <%= form_with model: @setting, url: update_settings_path, local: true do |f| %>
  	<div class="form-group">
	  	<%= f.label :name, "Name of the blog" %>
	  	<%= f.text_field :name, class: 'form-control' %>
	  	<small id="emailHelp" class="form-text text-muted">Please provide a name for your blog.</small>
  	</div>


  	<div class="form-group">
	  	<%= f.label :disqus_id, "Disqus short-name" %>
	  	<%= f.text_field :disqus_id, class: 'form-control' %>
	  	<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  	</div>

  	<div class="form-group">
	  	<%= f.label :g_analytics, "Google analytics ID" %>
	  	<%= f.text_field :g_analytics, class: 'form-control' %>
	  	<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  	</div>

  	<div class="row col-4">
	  	<%= f.label :post_page, "Articles per page" %>
	  	<%= f.number_field :post_page, class: 'form-control' %>
	  	<small id="emailHelp" class="form-text text-muted">Provide how many default articles per page at root.</small>
  	</div>

		<br>  		
    <%= f.submit "Save", class: "btn btn-primary btn-round" %>


	<% end %>

</div>